#!/bin/bash
#jakoped:L00p2oo1@stcweb.statcan.ca:80
read RESPONSE <<< $(curl --proxy jakoped:L00p2oo1@stcweb.statcan.ca:80 -s http://data.statcan.gc.ca/data/api/action/organization_show -d '{"id": "cra"}')
echo  $RESPONSE

